---
- name: epel-release repo
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: install java 1.8.0
  yum:
    name: java-1.8.0
    state: latest
