---
- name: add a sonarqube user 
  user:
    name: sonarqube

- name: sonar file present 
  stat:
    path: /opt/sonarqube
  register: sonar_opt_path

- name: download sonarqube file from
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.6.zip
    dest: /opt/
    remote_src: yes
  when: sonar_opt_path.stat.exists == False

- name: check if sonaraqube-*
  stat:
    path: /opt/sonarqube-7.6
  register: sonar_path

- name: move the folder 
  command: mv /opt/sonarqube-7.6 /opt/sonarqube
  when: sonar_path.stat.exists

- name: change owner of sonarqube 
  file:
    path: /opt/sonarqube
    owner: sonarqube
    recurse: yes
